name: The WebKitGTK+ Project
url: http://webkitgtk.org
exclude: ['README.md', 'generate-site', 'releases', 'webkit-release', 'planet', 'generate-planet']

stable-release-version: 2.0.1
unstable-release-version: 1.11.92
