name: The WebKitGTK+ Project
url: http://webkitgtk.org
exclude: ['README.md', 'generate-site', 'releases', 'webkit-release', 'planet', 'generate-planet']

stable-release-version: 2.6.2
unstable-release-version: 2.5.90
